---
cgit_url: http://bogomips.org/sleepy_penguin.git
git_url: git://bogomips.org/sleepy_penguin.git
rdoc_url: http://bogomips.org/sleepy_penguin/
private_email: sleepy.penguin@bogomips.org
public_email: sleepy.penguin@librelist.org
